layout_defs = {
    -- TODO
    ['TODO remove lbl'] = {2, 4, 20, 0, false, nil},
    ['TODO remove label'] = {4, 4, 20, 0, false, nil},

    -- CNI
    ['UHF Mode Rotary'] = {1, 1, 3, 0, false, nil},
    ['UHF IncDecSymbol'] = {1, 5, 1, 0, false, nil},
    ['Selected UHF Frequency'] = {1, 6, 6, 0, false, nil},
    ['Steerpoint Use'] = {1, 14, 4, 0, false, nil},
    ['WPT IncDecSymbol'] = {1, 19, 1, 0, false, nil},
    ['Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['UHF Status'] = {2, 1, 1, 0, false, nil},
    ['Default Value Indication'] = {2, 11, 1, 0, false, nil},
    ['Wind Magnetic Direction'] = {2, 16, 2, 0, false, nil},
    ['Wind Speed'] = {2, 20, 2, 0, false, nil},
    ['VHF Label'] = {3, 1, 3, 0, false, nil},
    ['VHF IncDecSymbol'] = {3, 5, 1, 0, false, nil},
    ['Selected VHF Frequency'] = {3, 6, 6, 0, false, nil},
    ['System Time'] = {3, 15, 8, 0, false, nil},
    ['VHF Status'] = {4, 1, 1, 0, false, nil},
    ['Hack Time'] = {4, 15, 8, 0, false, nil},
    ['IFF Modes Label'] = {5, 1, 1, 0, false, nil},
    ['IFF Modes Enabled'] = {5, 2, 6, 0, false, nil},
    ['Active Mode 3 Code'] = {5, 9, 4, 0, false, nil},
    ['IFF Switching'] = {5, 14, 1, 0, false, nil},
    ['TACAN Label'] = {5, 19, 1, 0, false, nil},
    ['TACAN Channel'] = {5, 20, 3, 0, false, nil},
    ['TACAN Band'] = {5, 23, 1, 0, false, nil},
    ['TACAN A-A Distance'] = {5, 19, 5, 0, false, nil},

    -- COM
    ['Secure Voice'] = {1, 1, 3, 0, false, nil},
    ['COM 1 Mode'] = {1, 5, 3, 0, false, nil},
    ['Receiver Mode'] = {1, 13, 4, 0, false, nil},
    ['COM 1 Power Status'] = {1, 13, 2, 0, false, nil},
    ['COM 2 Mode'] = {1, 9, 3, 0, false, nil},
    ['COM 2 Mode Voice'] = {1, 8, 3, 0, false, nil},
    ['Receiver Power Status'] = {1, 15, 2, 0, false, nil},
    ['GUARD VHF Label'] = {1, 8, 3, 0, false, nil},
    ['GUARD COM 2 Receiver Mode'] = {1, 13, 2, 0, false, nil},
    ['Active Frequency or Channel'] = {2, 2, 6, 0, false, nil},
    ['Active Frequency or Channe'] = {2, 2, 6, 0, false, nil},
    ['Scratchpad'] = {3, 14, 6, 0, false, nil},
    ['Asterisks on Scratchpad_both'] = {3, 13, 1, 20, true, nil},
    ['Guard or Backup Status'] = {3, 9, 5, 0, false, nil},
    ['GUARD COM 2 Receiver Band'] = {3, 8, 2, 0, false, nil},
    ['GUARD Guard Label'] = {3, 12, 5, 0, false, nil},
    ['Preset Label'] = {4, 2, 9, 0, false, nil},
    ['Preset Number'] = {4, 7, 2, 0, false, nil},
    ['Asterisks on PresetChannel_both'] = {4, 6, 1, 9, true, nil},
    ['TOD Label'] = {4, 17, 3, 0, false, nil},
    ['Preset Frequency'] = {5, 5, 6, 0, false, nil},
    ['Asterisks on PresetFrequency_both'] = {5, 4, 1, 11, true, nil},
    ['Bandwidth'] = {5, 18, 2, 0, false, nil},
    ['Asterisks on Band_both'] = {5, 17, 1, 20, true, nil},
    ['Preset Channel Number'] = {5, 20, 2, 0, false, nil},
    ['Guard or Backup Frequency'] = {5, 10, 6, 0, false, nil},

    -- IFF
    ['STAT IFF label'] = {1, 1, 3, 0, false, nil},
    ['STAT IFF Power Status'] = {1, 5, 3, 0, false, nil},
    ['STAT Mode label'] = {1, 12, 3, 0, false, nil},
    ['STAT Event Occured'] = {1, 18, 3, 0, false, nil},
    ['POS IFF label'] = {1, 1, 3, 0, false, nil},
    ['POS IFF Power Status'] = {1, 5, 3, 0, true, nil},
    ['POS Event Occured'] = {1, 18, 3, 0, true, nil},
    ['POS Mode Group State'] = {1, 22, 1, 0, false, nil},
    ['POS IncDec Symbol'] = {1, 23, 1, 0, false, nil},
    ['TIM IFF label'] = {1, 1, 3, 0, false, nil},
    ['TIM IFF Power Status'] = {1, 5, 3, 0, false, nil},
    ['TIM Event Occured'] = {1, 18, 3, 0, true, nil},
    ['TIM Code Group State'] = {1, 22, 1, 0, false, nil},
    ['TIM IncDec Symbol'] = {1, 23, 1, 0, false, nil},
    ['IFF label'] = {1, 8, 3, 0, false, nil},
    ['IFF Status'] = {1, 12, 4, 0, false, nil},
    ['STAT Mode Asterisks_both'] = {2, 17, 1, 23, true, nil},
    ['STAT Mode Scratchpad'] = {2, 18, 5, 0, false, nil},
    ['STAT M1 Mode'] = {3, 0, 2, 0, false, nil},
    ['STAT M1 Lockout Status'] = {3, 3, 1, 0, false, nil},
    ['STAT M1 Code'] = {3, 4, 2, 0, false, nil},
    ['STAT M4 Mode'] = {3, 8, 2, 0, false, nil},
    ['STAT M4 Code'] = {3, 12, 1, 0, false, nil},
    ['STAT M4 Key'] = {3, 14, 3, 0, false, nil},
    ['STAT POS EVENT - Side'] = {3, 19, 1, 0, false, nil},
    ['STAT POS EVENT - OF'] = {3, 20, 2, 0, false, nil},
    ['STAT POS EVENT - Number'] = {3, 22, 1, 0, false, nil},
    ['POS M1 Mode'] = {3, 1, 2, 0, false, nil},
    ['POS M1 Lockout Status'] = {3, 3, 1, 0, false, nil},
    ['POS M1 Code'] = {3, 4, 5, 0, false, nil},
    ['POS M4 Mode'] = {3, 9, 2, 0, false, nil},
    ['POS M4 Code'] = {3, 13, 1, 0, false, nil},
    ['POS M4 Key'] = {3, 14, 2, 0, false, nil},
    ['POS Mode Asterisks_both'] = {3, 18, 1, 23, true, nil},
    ['POS Mode Scratchpad'] = {3, 14, 5, 0, false, nil},
    ['TIM M1 Mode'] = {3, 1, 2, 0, false, nil},
    ['TIM M1 Lockout Status'] = {3, 3, 1, 0, false, nil},
    ['TIM M1 Code'] = {3, 4, 5, 0, false, nil},
    ['TIM M4 Mode'] = {3, 9, 2, 0, false, nil},
    ['TIM M4 Code'] = {3, 13, 1, 0, false, nil},
    ['TIM M4 Key'] = {3, 14, 2, 0, false, nil},
    ['TIM Mode Asterisks_both'] = {3, 18, 1, 23, true, nil},
    ['TIM Mode Scratchpad'] = {3, 14, 5, 0, false, nil},
    ['BACKUP label'] = {3, 9, 6, 0, false, nil},
    ['STAT M2 Mode'] = {4, 0, 2, 0, false, nil},
    ['STAT M2 Lockout Status'] = {4, 3, 1, 0, false, nil},
    ['STAT M2 Code'] = {4, 4, 4, 0, false, nil},
    ['STAT MC Mode'] = {4, 9, 2, 0, false, nil},
    ['STAT MC Code'] = {4, 12, 1, 0, false, nil},
    ['STAT MC Key'] = {4, 14, 3, 0, false, nil},
    ['STAT M2 Mode'] = {4, 0, 2, 0, false, nil},
    ['STAT M2 Lockout Status'] = {4, 3, 1, 0, false, nil},
    ['STAT M2 Code'] = {4, 4, 4, 0, false, nil},
    ['STAT MC Mode'] = {4, 9, 2, 0, false, nil},
    ['STAT MC Code'] = {4, 12, 1, 0, false, nil},
    ['STAT MC Key'] = {4, 14, 3, 0, false, nil},
    ['STAT TIM EVENT - Time'] = {4, 18, 5, 0, false, nil},
    ['POS M2 Mode'] = {4, 1, 2, 0, false, nil},
    ['POS M2 Lockout Status'] = {4, 3, 1, 0, false, nil},
    ['POS M2 Code'] = {4, 4, 4, 0, false, nil},
    ['POS MC Mode'] = {4, 9, 2, 0, false, nil},
    ['POS MC Code'] = {4, 12, 1, 0, false, nil},
    ['POS MC Key'] = {4, 14, 3, 0, false, nil},
    ['POS POS EVENT - Side'] = {4, 19, 1, 0, false, nil},
    ['POS POS EVENT - OF'] = {4, 20, 2, 0, false, nil},
    ['POS POS EVENT - Number'] = {4, 22, 1, 0, false, nil},
    ['TIM M2 Mode'] = {4, 1, 2, 0, false, nil},
    ['TIM M2 Lockout Status'] = {4, 3, 1, 0, false, nil},
    ['TIM M2 Lockout Status'] = {4, 4, 4, 0, false, nil},
    ['TIM MC Mode'] = {4, 9, 2, 0, false, nil},
    ['TIM MC Code'] = {4, 12, 1, 0, false, nil},
    ['TIM MC Key'] = {4, 14, 3, 0, false, nil},
    ['TIM EVENT - Time'] = {4, 18, 5, 0, false, nil},
    ['STAT M3 Mode'] = {5, 0, 2, 0, false, nil},
    ['STAT M3 Lockout Status'] = {5, 3, 1, 0, false, nil},
    ['STAT M3 Code'] = {5, 4, 4, 0, false, nil},
    ['STAT M4 Monitoring'] = {5, 9, 3, 0, false, nil},
    ['STAT M4 Monitoring Key'] = {5, 14, 3, 0, false, nil},
    ['STAT MS Mode'] = {5, 18, 2, 0, false, nil},
    ['STAT MS Code'] = {5, 20, 1, 0, false, nil},
    ['STAT MS Key'] = {5, 21, 3, 0, false, nil},
    ['POS M3 Mode'] = {5, 1, 2, 0, false, nil},
    ['POS M3 Lockout Status'] = {5, 3, 1, 0, false, nil},
    ['POS M3 Code'] = {5, 4, 4, 0, false, nil},
    ['POS M4 Monitoring'] = {5, 9, 3, 0, false, nil},
    ['POS M4 Monitoring Key'] = {5, 14, 3, 0, false, nil},
    ['POS MS Mode'] = {5, 18, 2, 0, false, nil},
    ['POS MS Code'] = {5, 20, 1, 0, false, nil},
    ['POS MS Key'] = {5, 21, 3, 0, false, nil},
    ['TIM M3 Mode'] = {5, 1, 2, 0, false, nil},
    ['TIM M3 Lockout Status'] = {5, 3, 1, 0, false, nil},
    ['TIM M3 Code'] = {5, 4, 4, 0, false, nil},
    ['TIM M4 Monitoring'] = {5, 9, 3, 0, false, nil},
    ['TIM M4 Monitoring Key'] = {5, 14, 3, 0, false, nil},
    ['TIM MS Mode'] = {5, 18, 2, 0, false, nil},
    ['TIM MS Code'] = {5, 20, 1, 0, false, nil},
    ['TIM MS Key'] = {5, 21, 3, 0, false, nil},

    -- List
    ['LIST LIST Label'] = {1, 10, 4, 0, false, nil},
    ['LIST Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['LIST WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['LIST List Item 1 Number'] = {2, 0, 1, 0, true, nil},
    ['LIST List Item 1 Name'] = {2, 1, 4, 0, false, nil},
    ['LIST List Item 2 Number'] = {2, 6, 1, 0, true, nil},
    ['LIST List Item 2 Name'] = {2, 7, 4, 0, false, nil},
    ['LIST List Item 3 Number'] = {2, 12, 1, 0, true, nil},
    ['LIST List Item 3 Name'] = {2, 13, 4, 0, false, nil},
    ['LIST List Item R Number'] = {2, 18, 1, 0, true, nil},
    ['LIST List Item R Name'] = {2, 19, 4, 0, false, nil},
    ['LIST List Item 4 Number'] = {3, 0, 1, 0, true, nil},
    ['LIST List Item 4 Name'] = {3, 1, 4, 0, false, nil},
    ['LIST List Item 5 Number'] = {3, 6, 1, 0, true, nil},
    ['LIST List Item 5 Name'] = {3, 7, 4, 0, false, nil},
    ['LIST List Item 6 Number'] = {3, 12, 1, 0, true, nil},
    ['LIST List Item 6 Name'] = {3, 13, 4, 0, false, nil},
    ['LIST List Item E Number'] = {3, 18, 1, 0, true, nil},
    ['LIST List Item E Name'] = {3, 19, 4, 0, false, nil},
    ['LIST List Item 7 Number'] = {4, 0, 1, 0, true, nil},
    ['LIST List Item 7 Name'] = {4, 1, 4, 0, false, nil},
    ['LIST List Item 8 Number'] = {4, 6, 1, 0, true, nil},
    ['LIST List Item 8 Name'] = {4, 7, 4, 0, false, nil},
    ['LIST List Item 9 Number'] = {4, 12, 1, 0, true, nil},
    ['LIST List Item 9 Name'] = {4, 13, 4, 0, false, nil},
    ['LIST List Item 0 Number'] = {4, 18, 1, 0, true, nil},
    ['LIST List Item 0 Name'] = {4, 19, 4, 0, false, nil},

    -- T-ILS
    ['TCN Label'] = {1, 1, 3, 0, false, nil},
    ['TCN Mode'] = {1, 5, 3, 0, false, nil},
    ['TCN BIG OFF Label'] = {1, 5, 3, 0, false, 'OFF'},
    ['ILS Label'] = {1, 13, 3, 0, false, nil},
    ['ILS Mode'] = {1, 18, 3, 0, false, nil},
    ['TILS Scratchpad'] = {3, 8, 6, 0, false, nil},
    ['TILS Asterisks_both'] = {3, 7, 1, 14, true, nil},
    ['ILS CMD STRG'] = {3, 15, 8, 0, false, nil},
    ['TCN BCN Label'] = {3, 0, 3, 0, false, nil},
    ['TCN BCN ID'] = {3, 4, 3, 0, false, nil},
    ['ILS FRQ Label'] = {4, 12, 3, 0, false, nil},
    ['ILS FRQ Scratchpad'] = {4, 17, 6, 0, false, nil},
    ['ILS FRQ Asterisks_both'] = {4, 16, 1, 23, true, nil},
    ['TCN CHAN Label'] = {4, 0, 4, 0, false, nil},
    ['TCN CHAN Scratchpad'] = {4, 5, 3, 0, false, nil},
    ['TCN CHAN Asterisks_both'] = {4, 4, 1, 8, true, nil},
    ['BACKUP lbl'] = {4, 2, 6, 0, false, nil},
    ['ILS CRS Label'] = {5, 12, 3, 0, false, nil},
    ['ILS CRS Scratchpad'] = {5, 17, 4, 0, false, nil},
    ['ILS CRS Asterisks_both'] = {5, 16, 1, 21, true, nil},
    ['TCN BAND Label'] = {5, 0, 4, 0, false, nil},
    ['TCN BAND XY'] = {5, 5, 1, 0, false, nil},
    ['TCN BAND Key'] = {5, 6, 3, 0, false, nil},

    -- ALOW
    ['ALOW ALOW label'] = {1, 10, 4, 0, false, nil},
    ['ALOW Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['ALOW WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['ALOW CARA ALOW label'] = {3, 3, 9, 0, false, nil},
    ['ALOW CARA ALOW Scratchpad'] = {3, 15, 7, 0, false, nil},
    ['ALOW CARA ALOW Asterisks_both'] = {3, 14, 1, 22, true, nil},
    ['ALOW MSL FLOOR label'] = {4, 3, 9, 0, false, nil},
    ['ALOW MSL FLOOR Scratchpad'] = {4, 15, 7, 0, false, nil},
    ['ALOW MSL FLOOR Asterisks_both'] = {4, 14, 1, 22, true, nil},

    -- STPT
    ['STEERPOINT LABEL'] = {1, 6, 4, 0, false, nil},
    ['STEERPOINT NUMBER'] = {1, 12, 3, 0, false, nil},
    ['STEERPOINT IncDecSymbol'] = {1, 16, 1, 0, false, nil},
    ['STEERPOINT SEQUENCE'] = {1, 18, 4, 0, false, nil},
    ['STEERPOINT NUMBER Asteriscs_both'] = {1, 11, 1, 15, true, nil},
    ['STEERPOINT SEQUENCE Asteriscs_both'] = {1, 17, 1, 22, true, nil},
    ['STEERPOINT Latitude'] = {2, 3, 3, 0, false, nil},
    ['STEERPOINT Latitude Value'] = {2, 8, 12, 0, false, nil},
    ['STEERPOINT Latitude Asteriscs_both'] = {2, 7, 1, 20, true, nil},
    ['STEERPOINT Longitude'] = {3, 3, 3, 0, false, nil},
    ['STEERPOINT Longitude Value'] = {3, 8, 12, 0, false, nil},
    ['STEERPOINT Longitude Asteriscs_both'] = {3, 7, 1, 20, true, nil},
    ['STEERPOINT Elevation'] = {4, 2, 3, 0, false, nil},
    ['STEERPOINT Elevation Value'] = {4, 8, 8, 0, false, nil},
    ['STEERPOINT Elevation Asteriscs_both'] = {4, 7, 1, 16, true, nil},
    ['STEERPOINT Time over current STP'] = {5, 3, 3, 0, false, nil},
    ['STEERPOINT TOS Value'] = {5, 8, 8, 0, false, nil},
    ['STEERPOINT TOS Asteriscs_both'] = {5, 7, 1, 16, true, nil},

    -- STPT MGRS
    ['STEERPOINT UTM LABEL'] = {1, 2, 3, 0, false, nil},
    ['STEERPOINT GRID'] = {2, 6, 4, 0, false, nil},
    ['STEERPOINT GRID DIGIT Value'] = {2, 12, 2, 0, false, nil},
    ['STEERPOINT GRID SYMBOL Value'] = {2, 14, 1, 0, false, nil},
    ['STEERPOINT GRID DIGIT Asteriscs_both'] = {2, 11, 1, 15, true, nil},
    ['STEERPOINT GRID SYMBOL Asteriscs_both'] = {2, 11, 1, 15, true, nil},
    ['STEERPOINT GRID CNVRT'] = {2, 17, 5, 0, false, nil},
    ['STEERPOINT CNVRT Asteriscs_both'] = {2, 16, 1, 22, true, nil},
    ['STEERPOINT SQUARE'] = {3, 4, 6, 0, false, nil},
    ['STEERPOINT SQUARE Value1'] = {3, 12, 1, 0, false, nil},
    ['STEERPOINT SQUARE Value2'] = {3, 13, 1, 0, false, nil},
    ['STEERPOINT SQUARE Asteriscs_both'] = {3, 11, 1, 14, true, nil},
    ['STEERPOINT SQUARE2 Asteriscs_both'] = {3, 11, 1, 14, true, nil},
    ['STEERPOINT EAST NORTH'] = {4, 0, 10, 0, false, nil},
    ['STEERPOINT EAST NORTH Value'] = {4, 12, 11, 0, false, nil},
    ['STEERPOINT EAST NORTH Asteriscs_both'] = {4, 11, 1, 23, true, nil},
    ['STEERPOINT ElevationMGRS'] = {5, 6, 4, 0, false, nil},
    ['STEERPOINT ElevationMGRS Value'] = {5, 11, 8, 0, false, nil},
    ['STEERPOINT ElevationMGRS Asteriscs_both'] = {5, 11, 1, 20, true, nil},

    -- TIME
    ['TIME_label'] = {1, 9, 4, 0, false, nil},
    ['SYSTEM_label'] = {2, 4, 6, 0, false, nil},
    ['GPS_SYSTEM_label'] = {2, 0, 10, 0, false, nil},
    ['SYSTEM_value'] = {2, 13, 8, 0, false, nil},
    ['Asterisks_on_SYSTEM_both'] = {2, 12, 1, 21, true, nil},
    ['HACK_label'] = {3, 6, 4, 0, false, nil},
    ['HACK_value'] = {3, 13, 8, 0, false, nil},
    ['Asterisks_on_HACK_both'] = {3, 12, 1, 21, true, nil},
    ['HACK_IncDecSymbol'] = {3, 23, 1, 0, false, nil},
    ['DELTA_TOS_label'] = {4, 1, 9, 0, false, nil},
    ['DELTA_TOS_value'] = {4, 12, 9, 0, false, nil},
    ['Asterisks_on_DELTA_TOS_both'] = {4, 11, 1, 21, true, nil},
    ['DATE_FORMAT_label'] = {5, 2, 8, 0, false, nil},
    ['DATE_value'] = {5, 13, 8, 0, false, nil},
    ['Asterisks_on_DATE_both'] = {5, 12, 1, 21, true, nil},

    -- BINGO
    ['BINGO label'] = {1, 9, 5, 0, false, nil},
    ['BINGO STPT Num'] = {1, 20, 2, 0, false, nil},
    ['BINGO IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['SET label'] = {3, 6, 3, 0, false, nil},
    ['BINGO Asterisks_both'] = {3, 10, 1, 19, true, nil},
    ['BINGO Scratchpad'] = {3, 11, 8, 0, false, nil},
    ['TOTAL label'] = {4, 4, 5, 0, false, nil},
    ['TOTAL value'] = {4, 11, 5, 0, false, nil},
    ['TOTAL LBS label'] = {4, 16, 3, 0, false, nil},

    -- NAV
    ['NAV STATUS NAV Status lbl'] = {1, 7, 10, 0, false, nil},
    ['NAV COMMANDS NAV Status lbl'] = {1, 6, 12, 0, false, nil},
    ['NAV STATUS INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['NAV STATUS INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['NAV COMMANDS INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['NAV COMMANDS INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['NAV STATUS SYS ACCURACY label'] = {2, 3, 9, 0, false, nil},
    ['NAV STATUS SYS ACCURACY value'] = {2, 14, 4, 0, false, nil},
    ['NAV STATUS GPS ACCURACY label'] = {3, 3, 9, 0, false, nil},
    ['NAV STATUS GPS ACCURACY value'] = {3, 14, 5, 0, false, nil},
    ['NAV COMMANDS FILTER MODE label'] = {3, 3, 11, 0, false, nil},
    ['NAV COMMANDS FILTER MODE value'] = {3, 16, 4, 0, false, nil},
    ['NAV COMMANDS Asterisks_both'] = {3, 15, 1, 20, true, nil},
    ['NAV STATUS MSN DUR label'] = {4, 3, 7, 0, false, nil},
    ['NAV STATUS DAYS label'] = {4, 16, 4, 0, false, nil},
    ['NAV STATUS Scratchpad'] = {4, 12, 2, 0, false, nil},
    ['NAV STATUS Asterisks on Scratchpad_both'] = {4, 11, 1, 14, true, nil},
    ['NAV COMMANDS RESET GPS label'] = {4, 6, 11, 0, false, nil},
    ['NAV COMMANDS Asterisks on RESET_both'] = {4, 5, 1, 17, true, nil},
    ['NAV STATUS Keys Msg'] = {5, 3, 18, 0, false, nil},
    ['NAV COMMANDS ZEROIZE GPS label'] = {5, 6, 11, 0, false, nil},
    ['NAV COMMANDS Asterisks on ZEROIZE_both'] = {5, 5, 1, 17, true, nil},

    -- MAN
    ['MAN Label'] = {1, 10, 3, 0, false, nil},
    ['MAN STPT Num'] = {1, 20, 2, 0, false, nil},
    ['MAN IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['WSPAN Label'] = {2, 6, 5, 0, false, nil},
    ['WSPAN DATA'] = {2, 13, 5, 0, false, nil},
    ['WSPAN Asteriscs_both'] = {2, 12, 1, 18, true, nil},
    ['MBAL Label'] = {3, 10, 4, 0, false, nil},
    ['RNG Label'] = {4, 8, 3, 0, false, nil},
    ['RNG Data'] = {4, 11, 7, 0, false, nil},
    ['RNG FT'] = {4, 18, 2, 0, false, nil},
    ['TOF Label'] = {5, 8, 3, 0, false, nil},
    ['TOF Data'] = {5, 11, 6, 0, false, nil},
    ['TOF SEC'] = {5, 17, 3, 0, false, nil},

    -- INS
    ['INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['INS_lbl'] = {1, 2, 3, 0, false, nil},
    ['INS_AlignTime'] = {1, 7, 4, 0, false, nil},
    ['INS_AlignSlash'] = {1, 11, 1, 0, false, nil},
    ['INS_AlignStatusCode'] = {1, 12, 2, 0, false, nil},
    ['INS_Ready'] = {1, 15, 3, 0, false, nil},
    ['INFLT ALGN INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['INFLT ALGN INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['INFLT ALGN INS_lbl'] = {1, 4, 3, 0, false, nil},
    ['INFLT ALGN INS_INFLT_ALGN_lbl'] = {1, 8, 10, 0, false, nil},
    ['INS_LAT_lbl'] = {2, 2, 3, 0, false, nil},
    ['INS_LAT_Scratchpad'] = {2, 7, 10, 0, false, nil},
    ['Asterisks_on_LAT_Scratchpad_both'] = {2, 6, 1, 17, true, nil},
    ['INS_LNG_lbl'] = {3, 2, 3, 0, false, nil},
    ['INS_LNG_Scratchpad'] = {3, 7, 10, 0, false, nil},
    ['Asterisks_on_LNG_Scratchpad_both'] = {3, 6, 1, 17, true, nil},
    ['INFLT ALGN INS_COMPASS_HDG_lbl'] = {3, 3, 11, 0, false, nil},
    ['INFLT ALGN INS_CompassHdgScratchpad'] = {3, 16, 4, 0, false, nil},
    ['INFLT ALGN Asterisks on Scratchpad_both'] = {3, 15, 1, 20, true, nil},
    ['INS_SALT_lbl'] = {4, 1, 4, 0, false, nil},
    ['INS_SALT_Scratchpad'] = {4, 8, 7, 0, false, nil},
    ['Asterisks_on_SALT_Scratchpad_both'] = {4, 7, 1, 15, true, nil},
    ['INS_FIX_NECESSARY_lbl'] = {4, 3, 17, 0, false, nil},
    ['INS_THDG_lbl'] = {5, 1, 4, 0, false, nil},
    ['INS_THDG_Scratchpad'] = {5, 7, 6, 0, false, nil},
    ['Asterisks_on_THDG_Scratchpad'] = {5, 6, 1, 13, true, nil},
    ['INS_GS_lbl'] = {5, 16, 3, 0, false, nil},
    ['INS_GS_value'] = {5, 20, 3, 0, false, nil},

    -- CMDS
    ['CMDS_Prog_label'] = {1, 15, 4, 0, false, nil},
    ['CMDS_Selected_Program'] = {1, 21, 2, 0, false, nil},
    ['CMDS_Prog_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['CMDS  BINGO CMDS_BINGO_label'] = {1, 5, 11, 0, false, nil},
    ['CMDS  BINGO Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['CMDS  BINGO WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['CMDS_CHAFF_label'] = {1, 2, 9, 0, false, nil},
    ['CMDS_FLARE_label'] = {1, 2, 9, 0, false, nil},
    ['CMDS_OTHER1_label'] = {1, 2, 10, 0, false, nil},
    ['CMDS_OTHER2_label'] = {1, 2, 10, 0, false, nil},
    ['CMDS_BQ_lbl'] = {2, 6, 2, 0, false, nil},
    ['CMDS_BQ_Scratchpad'] = {2, 10, 2, 0, false, nil},
    ['CMDS_BQ_Asterisks_both'] = {2, 9, 1, 12, true, nil},
    ['CMDS  BINGO CMDS_CH_lbl'] = {2, 2, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_CH_Scratchpad'] = {2, 7, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_CH_Asterisks_both'] = {2, 6, 1, 9, true, nil},
    ['CMDS_BI_lbl'] = {3, 6, 2, 0, false, nil},
    ['CMDS_BI_Scratchpad'] = {3, 10, 6, 0, false, nil},
    ['CMDS_BI_Asterisks_both'] = {3, 9, 1, 16, true, nil},
    ['CMDS  BINGO CMDS_FL_lbl'] = {3, 2, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_FL_Scratchpad'] = {3, 7, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_FL_Asterisks_both'] = {3, 6, 1, 9, true, nil},
    ['CMDS  BINGO CMDS_FDBK_lbl'] = {3, 11, 4, 0, false, nil},
    ['CMDS  BINGO CMDS_FDBK_value'] = {3, 19, 3, 0, false, nil},
    ['CMDS  BINGO CMDS_FDBK_Asterisks_both'] = {3, 18, 1, 22, true, nil},
    ['CMDS_SQ_lbl'] = {4, 6, 2, 0, false, nil},
    ['CMDS_SQ_Scratchpad'] = {4, 10, 2, 0, false, nil},
    ['CMDS_SQ_Asterisks_both'] = {4, 9, 1, 12, true, nil},
    ['CMDS  BINGO CMDS_O1_lbl'] = {4, 2, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_O1_Scratchpad'] = {4, 7, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_O1_Asterisks_both'] = {4, 6, 1, 9, true, nil},
    ['CMDS  BINGO CMDS_REQCTR_lbl'] = {4, 11, 6, 0, false, nil},
    ['CMDS  BINGO CMDS_REQCTR_value'] = {4, 19, 3, 0, false, nil},
    ['CMDS  BINGO CMDS_REQCTR_Asterisks_both'] = {4, 18, 1, 22, true, nil},
    ['CMDS_SI_lbl'] = {5, 6, 2, 0, false, nil},
    ['CMDS_SI_Scratchpad'] = {5, 10, 6, 0, false, nil},
    ['CMDS_SI_Asterisks_both'] = {5, 9, 1, 16, true, nil},
    ['CMDS  BINGO CMDS_O2_lbl'] = {5, 2, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_O2_Scratchpad'] = {5, 7, 2, 0, false, nil},
    ['CMDS  BINGO CMDS_O2_Asterisks_both'] = {5, 6, 1, 9, true, nil},
    ['CMDS  BINGO CMDS_BINGO_lbl'] = {5, 11, 5, 0, false, nil},
    ['CMDS  BINGO CMDS_BINGO_value'] = {5, 19, 3, 0, false, nil},
    ['CMDS  BINGO CMDS_BINGO_Asterisks_both'] = {5, 18, 1, 22, true, nil},

    -- Mode
    ['MODE Master_mode_label'] = {1, 4, 4, 0, false, nil},
    ['MODE Master_mode'] = {1, 10, 3, 0, false, nil},
    ['MODE Master_mode_ast_both'] = {1, 9, 1, 13, true, nil},
    ['MODE Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['MODE WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},

    -- DLNK
    ['TNDL LINK16 lbl'] = {1, 9, 4, 0, false, nil},
    ['TNDL Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['TNDL WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['NET STATUS NET STATUS lbl'] = {1, 5, 10, 0, false, nil},
    ['NET STATUS Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['NET STATUS WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['TNDL   STN LINK16 STN lbl'] = {1, 7, 10, 0, false, nil},
    ['TNDL   STN Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['TNDL   STN WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['AG DL lbl'] = {1, 7, 6, 0, false, nil},
    ['INTRAFLIGHT INTRAFLIGHT lbl'] = {1, 7, 11, 0, false, nil},
    ['TNDL FC lbl'] = {2, 3, 2, 0, false, nil},
    ['TNDL FC value'] = {2, 6, 3, 0, false, nil},
    ['TNDL Asterisks on FC_both'] = {2, 5, 1, 9, true, nil},
    ['TNDL CallSign Name char1'] = {2, 11, 1, 0, false, nil},
    ['TNDL CallSign Name char2'] = {2, 12, 1, 0, false, nil},
    ['TNDL Asterisks on CS Name_both'] = {2, 10, 1, 13, true, nil},
    ['TNDL VCS IncDecSymbol'] = {2, 14, 1, 0, false, nil},
    ['TNDL CallSign Number'] = {2, 16, 2, 0, false, nil},
    ['TNDL Asterisks on CS Number_both'] = {2, 15, 1, 18, true, nil},
    ['TNDL   STN STN id lbl_1'] = {2, 0, 1, 0, false, nil},
    ['TNDL   STN STN TDOA value_1'] = {2, 2, 1, 0, false, nil},
    ['TNDL   STN STN value_1'] = {2, 4, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_1_both'] = {2, 1, 1, 3, true, nil},
    ['TNDL   STN Asterisks on STN_1_both'] = {2, 3, 1, 9, true, nil},
    ['TNDL   STN STN id lbl_5'] = {2, 10, 2, 0, false, nil},
    ['TNDL   STN STN TDOA value_5'] = {2, 12, 1, 0, false, nil},
    ['TNDL   STN STN value_5'] = {2, 14, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_5_both'] = {2, 11, 1, 13, true, nil},
    ['TNDL   STN Asterisks on STN_5_both'] = {2, 13, 1, 19, true, nil},
    ['TNDL   STN OWN lbl'] = {2, 20, 3, 0, false, nil},
    ['NET STATUS GPS TIME lbl'] = {2, 0, 8, 0, false, nil},
    ['NET STATUS GPS TIME status'] = {2, 9, 3, 0, false, nil},
    ['NET STATUS Asterisks on ETR_both'] = {2, 8, 1, 12, true, nil},
    ['IPF Reset lbl'] = {2, 14, 9, 0, false, nil},
    ['Asterisks on IPF_both'] = {2, 13, 1, 23, true, nil},
    ['A-G DL XMT lbl'] = {2, 3, 3, 0, false, nil},
    ['A-G DL XMT value'] = {2, 7, 2, 0, false, nil},
    ['A-G DL COMM lbl'] = {2, 12, 4, 0, false, nil},
    ['A-G DL COMM status'] = {2, 17, 3, 0, false, nil},
    ['INTRAFLIGHT STN id lbl1'] = {2, 1, 2, 0, false, nil},
    ['INTRAFLIGHT STN value1'] = {2, 4, 5, 0, false, nil},
    ['INTRAFLIGHT STN id lbl5'] = {2, 7, 2, 0, false, nil},
    ['INTRAFLIGHT STN value5'] = {2, 10, 5, 0, false, nil},
    ['INTRAFLIGHT COMM lbl'] = {2, 13, 4, 0, false, nil},
    ['INTRAFLIGHT COMM status'] = {2, 18, 3, 0, false, nil},
    ['TNDL MC lbl'] = {3, 3, 2, 0, false, nil},
    ['TNDL MC value'] = {3, 6, 3, 0, false, nil},
    ['TNDL Asterisks on MC_both'] = {3, 5, 1, 9, true, nil},
    ['TNDL FL lbl'] = {3, 12, 2, 0, false, nil},
    ['TNDL FL status'] = {3, 16, 3, 0, false, nil},
    ['TNDL Asterisks on FL_both'] = {3, 15, 1, 19, true, nil},
    ['TNDL   STN NUM lbl'] = {3, 20, 1, 0, false, nil},
    ['TNDL   STN Own num value'] = {3, 22, 1, 0, false, nil},
    ['TNDL   STN Asterisks on Own_both'] = {3, 21, 1, 23, true, nil},
    ['NET STATUS TIME lbl'] = {3, 4, 4, 0, false, nil},
    ['NET STATUS TIME value'] = {3, 9, 8, 0, false, nil},
    ['NET STATUS Asterisks on TIME_both'] = {3, 8, 1, 17, true, nil},
    ['TNDL   STN STN id lbl_2'] = {3, 0, 1, 0, false, nil},
    ['TNDL   STN STN TDOA value_2'] = {3, 2, 1, 0, false, nil},
    ['TNDL   STN STN value_2'] = {3, 4, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_2_both'] = {3, 1, 1, 3, true, nil},
    ['TNDL   STN Asterisks on STN_2_both'] = {3, 3, 1, 9, true, nil},
    ['TNDL   STN STN id lbl_6'] = {3, 10, 2, 0, false, nil},
    ['TNDL   STN STN TDOA value_6'] = {3, 12, 1, 0, false, nil},
    ['TNDL   STN STN value_6'] = {3, 14, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_6_both'] = {3, 11, 1, 13, true, nil},
    ['TNDL   STN Asterisks on STN_6_both'] = {3, 13, 1, 19, true, nil},
    ['OWN value'] = {3, 7, 2, 0, false, nil},
    ['DATA lbl'] = {3, 12, 4, 0, false, nil},
    ['DATA value'] = {3, 7, 3, 0, false, nil},
    ['INTRAFLIGHT STN id lbl2'] = {3, 1, 2, 0, false, nil},
    ['INTRAFLIGHT STN value2'] = {3, 4, 5, 0, false, nil},
    ['INTRAFLIGHT STN id lbl6'] = {3, 7, 2, 0, false, nil},
    ['INTRAFLIGHT STN value6'] = {3, 10, 5, 0, false, nil},
    ['INTRAFLIGHT DATA lbl'] = {3, 13, 4, 0, false, nil},
    ['INTRAFLIGHT DATA value'] = {3, 18, 3, 0, false, nil},
    ['TNDL SC lbl'] = {4, 3, 2, 0, false, nil},
    ['TNDL SC value'] = {4, 6, 3, 0, false, nil},
    ['TNDL Asterisks on SC_both'] = {4, 5, 1, 9, true, nil},
    ['TNDL XMT lbl'] = {4, 11, 3, 0, false, nil},
    ['TNDL XMT status'] = {4, 16, 2, 0, false, nil},
    ['TNDL Asterisks on XMT_both'] = {4, 15, 1, 20, true, nil},
    ['NET STATUS NTR lbl'] = {4, 5, 3, 0, false, nil},
    ['NET STATUS NTR status'] = {4, 9, 3, 0, false, nil},
    ['NET STATUS Asterisks on NTR_both'] = {4, 8, 1, 12, true, nil},
    ['TNDL   STN STN id lbl_3'] = {4, 0, 1, 0, false, nil},
    ['TNDL   STN STN TDOA value_3'] = {4, 2, 1, 0, false, nil},
    ['TNDL   STN STN value_3'] = {4, 4, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_3_both'] = {4, 1, 1, 3, true, nil},
    ['TNDL   STN Asterisks on STN_3_both'] = {4, 3, 1, 9, true, nil},
    ['TNDL   STN STN id lbl_7'] = {4, 10, 2, 0, false, nil},
    ['TNDL   STN STN TDOA value_7'] = {4, 12, 1, 0, false, nil},
    ['TNDL   STN STN value_7'] = {4, 14, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_7_both'] = {4, 11, 1, 13, true, nil},
    ['TNDL   STN Asterisks on STN_7_both'] = {4, 13, 1, 19, true, nil},
    ['FILL lbl'] = {4, 2, 4, 0, false, nil},
    ['FILL status'] = {4, 7, 3, 0, false, nil},
    ['PRTL lbl'] = {4, 12, 4, 0, false, nil},
    ['PRTL status'] = {4, 17, 5, 0, false, nil},
    ['INTRAFLIGHT STN id lbl3'] = {4, 1, 2, 0, false, nil},
    ['INTRAFLIGHT STN value3'] = {4, 4, 5, 0, false, nil},
    ['INTRAFLIGHT STN id lbl7'] = {4, 7, 2, 0, false, nil},
    ['INTRAFLIGHT STN value7'] = {4, 10, 5, 0, false, nil},
    ['INTRAFLIGHT OWN lbl'] = {4, 14, 4, 0, false, nil},
    ['INTRAFLIGHT Own value'] = {4, 18, 2, 0, false, nil},
    ['TNDL P2 lbl'] = {5, 21, 3, 0, false, nil},
    ['NET STATUS SYNC lbl'] = {5, 4, 4, 0, false, nil},
    ['NET STATUS SYNC status'] = {5, 9, 4, 0, false, nil},
    ['NET STATUS Asterisks on SYNC_both'] = {5, 8, 1, 15, true, nil},
    ['NET STATUS P1 lbl'] = {5, 21, 3, 0, false, nil},
    ['TNDL   STN STN id lbl_4'] = {5, 0, 1, 0, false, nil},
    ['TNDL   STN STN TDOA value_4'] = {5, 2, 1, 0, false, nil},
    ['TNDL   STN STN value_4'] = {5, 4, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_4_both'] = {5, 1, 1, 3, true, nil},
    ['TNDL   STN Asterisks on STN_4_both'] = {5, 3, 1, 9, true, nil},
    ['TNDL   STN STN id lbl_8'] = {5, 10, 2, 0, false, nil},
    ['TNDL   STN STN TDOA value_8'] = {5, 12, 1, 0, false, nil},
    ['TNDL   STN STN value_8'] = {5, 14, 5, 0, false, nil},
    ['TNDL   STN Asterisks on STN TDOA_8_both'] = {5, 11, 1, 13, true, nil},
    ['TNDL   STN Asterisks on STN_8_both'] = {5, 13, 1, 19, true, nil},
    ['TNDL   STN P3 lbl'] = {5, 21, 3, 0, false, nil},
    ['P5 lbl'] = {5, 21, 3, 0, false, nil},
    ['INTRAFLIGHT STN id lbl4'] = {5, 1, 2, 0, false, nil},
    ['INTRAFLIGHT STN value4'] = {5, 4, 5, 0, false, nil},
    ['INTRAFLIGHT STN id lbl8'] = {5, 7, 2, 0, false, nil},
    ['INTRAFLIGHT STN value8'] = {5, 10, 5, 0, false, nil},
    ['INTRAFLIGHT LAST lbl'] = {5, 13, 4, 0, false, nil},
    ['INTRAFLIGHT LAST value'] = {5, 18, 2, 0, false, nil},
    ['INTRAFLIGHT P6 lbl'] = {5, 21, 3, 0, false, nil},

    -- Misc
    ['MISC MISC Label'] = {1, 10, 4, 0, false, nil},
    ['MISC Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['MISC WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['MISC Misc Item 1 Number'] = {2, 0, 1, 0, true, nil},
    ['MISC Misc Item 1 Name'] = {2, 1, 4, 0, false, nil},
    ['MISC Misc Item 2 Number'] = {2, 6, 1, 0, true, nil},
    ['MISC Misc Item 2 Name'] = {2, 7, 4, 0, false, nil},
    ['MISC Misc Item 3 Number'] = {2, 12, 1, 0, true, nil},
    ['MISC Misc Item 3 Name'] = {2, 13, 4, 0, false, nil},
    ['MISC Misc Item R Number'] = {2, 18, 1, 0, true, nil},
    ['MISC Misc Item R Name'] = {2, 19, 4, 0, false, nil},
    ['MISC Misc Item 4 Number'] = {3, 0, 1, 0, true, nil},
    ['MISC Misc Item 4 Name'] = {3, 1, 4, 0, false, nil},
    ['MISC Misc Item 5 Number'] = {3, 6, 1, 0, true, nil},
    ['MISC Misc Item 5 Name'] = {3, 7, 4, 0, false, nil},
    ['MISC Misc Item 6 Number'] = {3, 12, 1, 0, true, nil},
    ['MISC Misc Item 6 Name'] = {3, 13, 4, 0, false, nil},
    ['MISC Misc Item E Number'] = {3, 18, 1, 0, true, nil},
    ['MISC Misc Item E Name'] = {3, 19, 4, 0, false, nil},
    ['MISC Misc Item 7 Number'] = {4, 0, 1, 0, true, nil},
    ['MISC Misc Item 7 Name'] = {4, 1, 4, 0, false, nil},
    ['MISC Misc Item 8 Number'] = {4, 6, 1, 0, true, nil},
    ['MISC Misc Item 8 Name'] = {4, 7, 4, 0, false, nil},
    ['MISC Misc Item 9 Number'] = {4, 12, 1, 0, true, nil},
    ['MISC Misc Item 9 Name'] = {4, 13, 4, 0, false, nil},
    ['MISC Misc Item 0 Number'] = {4, 18, 1, 0, true, nil},
    ['MISC Misc Item 0 Name'] = {4, 19, 4, 0, false, nil},

    -- MAGV
    ['MAGV lbl'] = {1, 7, 4, 0, false, nil},
    ['MAGV Mode'] = {1, 13, 4, 0, false, nil},
    ['Asterisks_on_MAGV_Mode_both'] = {1, 12, 1, 17, true, nil},
    ['INS_MAGV_Scratchpad'] = {3, 9, 6, 0, false, nil},
    ['Asterisks_on_MAGV_Scratchpad_both'] = {3, 8, 1, 15, true, nil},

    -- LASER
    ['LASR LASR LABEL'] = {1, 11, 4, 0, false, nil},
    ['LASR Selected Steerpoint'] = {1, 20, 3, 0, false, nil},
    ['LASR WPT IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['LASR TGP CODE LABEL'] = {2, 1, 8, 0, false, nil},
    ['LASR TGP CODE VALUE'] = {2, 13, 4, 0, false, nil},
    ['LASR TGP CODE Asteriscs_both'] = {2, 12, 1, 17, true, nil},
    ['LASR LST CODE LABEL'] = {3, 1, 8, 0, false, nil},
    ['LASR LST CODE VALUE'] = {3, 13, 4, 0, false, nil},
    ['LASR LST CODE Asteriscs_both'] = {3, 12, 1, 17, true, nil},
    ['LASR Laser ST Time LABEL'] = {5, 1, 13, 0, false, nil},
    ['LASR Laser ST Time VALUE'] = {5, 16, 3, 0, false, nil},
    ['LASR Laser ST Time Asteriscs_both'] = {5, 15, 1, 19, true, nil},

    -- INTG
    ['INTG INTG label'] = {1, 13, 4, 0, false, nil},
    ['INTG INTG Mode'] = {1, 8, 4, 0, false, nil},
    ['INTG TIM Event'] = {1, 20, 3, 0, false, nil},
    ['INTG M1 Mode'] = {3, 0, 2, 0, false, nil},
    ['INTG M1 Decoupled Status'] = {3, 3, 1, 0, false, nil},
    ['INTG M1 Code'] = {3, 4, 2, 0, false, nil},
    ['INTG M4 Mode'] = {3, 16, 2, 0, false, nil},
    ['INTG M4 Decoupled Status'] = {3, 19, 1, 0, false, nil},
    ['INTG M4 Code'] = {3, 20, 1, 0, false, nil},
    ['INTG M4 Key'] = {3, 21, 3, 0, false, nil},
    ['INTG M2 Mode'] = {4, 0, 2, 0, false, nil},
    ['INTG M2 Decoupled Status'] = {4, 3, 1, 0, false, nil},
    ['INTG M2 Code'] = {4, 4, 4, 0, false, nil},
    ['INTG IJAM Mode'] = {4, 15, 4, 0, false, nil},
    ['INTG IJAM Key'] = {4, 20, 3, 0, false, nil},
    ['INTG M3 Mode'] = {5, 0, 2, 0, false, nil},
    ['INTG M3 Decoupled Status'] = {5, 3, 1, 0, false, nil},
    ['INTG M3 Code'] = {5, 4, 4, 0, false, nil},
    ['INTG Asterisks_both'] = {5, 9, 1, 15, true, nil},
    ['INTG Scratchpad'] = {5, 10, 5, 0, false, nil},
    ['INTG COUPLE Mode'] = {5, 16, 4, 0, false, nil},
    ['INTG COUPLE Key'] = {5, 20, 3, 0, false, nil},

    -- HARM
    ['HARM HARM'] = {1, 1, 4, 0, false, nil},
    ['HARM TblNum'] = {1, 6, 4, 0, false, nil},
    ['HARM Angles'] = {1, 10, 1, 0, false, nil},
    ['HARM T1'] = {1, 14, 2, 0, false, nil},
    ['HARM T1_code'] = {1, 18, 3, 0, false, nil},
    ['HARM Asterisks_T1_both'] = {1, 17, 1, 21, true, nil},
    ['HARM T2'] = {2, 14, 2, 0, false, nil},
    ['HARM T2_code'] = {2, 18, 3, 0, false, nil},
    ['HARM Asterisks_T2_both'] = {2, 17, 1, 21, true, nil},
    ['HARM T3'] = {3, 14, 2, 0, false, nil},
    ['HARM T3_code'] = {3, 18, 3, 0, false, nil},
    ['HARM Asterisks_T3_both'] = {3, 17, 1, 21, true, nil},
    ['HARM T4'] = {4, 14, 2, 0, false, nil},
    ['HARM T4_code'] = {4, 18, 3, 0, false, nil},
    ['HARM Asterisks_T4_both'] = {4, 17, 1, 21, true, nil},
    ['HARM T5'] = {5, 14, 2, 0, false, nil},
    ['HARM T5_code'] = {5, 18, 3, 0, false, nil},
    ['HARM Asterisks_T5_both'] = {5, 17, 1, 21, true, nil},

    -- VIP
    ['VIP-TO-TGT Visual initial point to TGT Label'] = {1, 6, 10, 0, false, nil},
    ['VIP-TO-TGT VIP to TGT Label Asteriscs_both'] = {1, 5, 1, 16, true, nil},
    ['VIP-TO-TGT Visual initial point number'] = {2, 5, 3, 0, false, nil},
    ['VIP-TO-TGT VIP number value'] = {2, 10, 3, 0, false, nil},
    ['VIP-TO-TGT VIP number up down arrows'] = {2, 14, 1, 0, false, nil},
    ['VIP-TO-TGT VIP number Asteriscs_both'] = {2, 9, 1, 13, true, nil},
    ['VIP-TO-TGT VIP bearing'] = {3, 4, 4, 0, false, nil},
    ['VIP-TO-TGT VIP bearing value'] = {3, 10, 6, 0, false, nil},
    ['VIP-TO-TGT VIP bearing Asteriscs_both'] = {3, 9, 1, 16, true, nil},
    ['VIP-TO-TGT Range'] = {4, 5, 3, 0, false, nil},
    ['VIP-TO-TGT Range value'] = {4, 12, 4, 0, false, nil},
    ['VIP-TO-TGT Range Asteriscs_both'] = {4, 11, 1, 16, true, nil},
    ['VIP-TO-TGT Range NM'] = {4, 17, 2, 0, false, nil},
    ['VIP-TO-TGT Elevation'] = {5, 4, 4, 0, false, nil},
    ['VIP-TO-TGT Elevation value'] = {5, 10, 8, 0, false, nil},
    ['VIP-TO-TGT Elevation Asteriscs_both'] = {5, 9, 1, 18, true, nil},

    -- VIP PUP
    ['VIP-TO-PUP Visual initial point to TGT Label'] = {1, 6, 10, 0, false, nil},
    ['VIP-TO-PUP VIP to TGT Label Asteriscs_both'] = {1, 5, 1, 16, true, nil},
    ['VIP-TO-PUP Visual initial point number'] = {2, 5, 3, 0, false, nil},
    ['VIP-TO-PUP VIP number value'] = {2, 10, 3, 0, false, nil},
    ['VIP-TO-PUP VIP number up down arrows'] = {2, 14, 1, 0, false, nil},
    ['VIP-TO-PUP VIP number Asteriscs_both'] = {2, 9, 1, 13, true, nil},
    ['VIP-TO-PUP VIP bearing'] = {3, 4, 4, 0, false, nil},
    ['VIP-TO-PUP VIP bearing value'] = {3, 10, 6, 0, false, nil},
    ['VIP-TO-PUP VIP bearing Asteriscs_both'] = {3, 9, 1, 16, true, nil},
    ['VIP-TO-PUP Range'] = {4, 5, 3, 0, false, nil},
    ['VIP-TO-PUP Range value'] = {4, 12, 4, 0, false, nil},
    ['VIP-TO-PUP Range Asteriscs_both'] = {4, 11, 1, 16, true, nil},
    ['VIP-TO-PUP Range NM'] = {4, 17, 2, 0, false, nil},
    ['VIP-TO-PUP Elevation'] = {5, 4, 4, 0, false, nil},
    ['VIP-TO-PUP Elevation value'] = {5, 10, 8, 0, false, nil},
    ['VIP-TO-PUP Elevation Asteriscs_both'] = {5, 9, 1, 18, true, nil},

    -- VRP
    ['TGT-TO-VRP Target to VRP Label'] = {1, 6, 10, 0, false, nil},
    ['TGT-TO-VRP Target to VRP Label Asteriscs_both'] = {1, 5, 1, 16, true, nil},
    ['TGT-TO-VRP Target number'] = {2, 5, 3, 0, false, nil},
    ['TGT-TO-VRP Target number value'] = {2, 10, 3, 0, false, nil},
    ['TGT-TO-VRP Target number up down arrows'] = {2, 14, 1, 0, false, nil},
    ['TGT-TO-VRP Target number Asteriscs_both'] = {2, 9, 1, 13, true, nil},
    ['TGT-TO-VRP Target bearing'] = {3, 4, 4, 0, false, nil},
    ['TGT-TO-VRP Target bearing value'] = {3, 10, 6, 0, false, nil},
    ['TGT-TO-VRP Target bearing Asteriscs_both'] = {3, 9, 1, 16, true, nil},
    ['TGT-TO-VRP Range'] = {4, 5, 3, 0, false, nil},
    ['TGT-TO-VRP Range value'] = {4, 10, 8, 0, false, nil},
    ['TGT-TO-VRP Range Asteriscs_both'] = {4, 9, 1, 18, true, nil},
    ['TGT-TO-VRP Range NM'] = {4, 17, 2, 0, false, nil},
    ['TGT-TO-VRP Elevation'] = {5, 4, 4, 0, false, nil},
    ['TGT-TO-VRP Elevation value'] = {5, 10, 8, 0, false, nil},
    ['TGT-TO-VRP Elevation Asteriscs_both'] = {5, 9, 1, 18, true, nil},

    -- VRP PUP
    ['TGT-TO-PUP Target to VRP Label'] = {1, 6, 10, 0, false, nil},
    ['TGT-TO-PUP Target to VRP Label Asteriscs_both'] = {1, 5, 1, 16, true, nil},
    ['TGT-TO-PUP Target number'] = {2, 5, 3, 0, false, nil},
    ['TGT-TO-PUP Target number value'] = {2, 10, 3, 0, false, nil},
    ['TGT-TO-PUP Target number up down arrows'] = {2, 14, 1, 0, false, nil},
    ['TGT-TO-PUP Target number Asteriscs_both'] = {2, 9, 1, 13, true, nil},
    ['TGT-TO-PUP Target bearing'] = {3, 4, 4, 0, false, nil},
    ['TGT-TO-PUP Target bearing value'] = {3, 10, 6, 0, false, nil},
    ['TGT-TO-PUP Target bearing Asteriscs_both'] = {3, 9, 1, 16, true, nil},
    ['TGT-TO-PUP Range'] = {4, 5, 3, 0, false, nil},
    ['TGT-TO-PUP Range value'] = {4, 10, 8, 0, false, nil},
    ['TGT-TO-PUP Range Asteriscs_both'] = {4, 9, 1, 18, true, nil},
    ['TGT-TO-PUP Range NM'] = {4, 17, 2, 0, false, nil},
    ['TGT-TO-PUP Elevation'] = {5, 4, 4, 0, false, nil},
    ['TGT-TO-PUP Elevation value'] = {5, 10, 8, 0, false, nil},
    ['TGT-TO-PUP Elevation Asteriscs_both'] = {5, 9, 1, 18, true, nil},

    -- HMCS
    ['HMCS DISPLAY HMCS_DISPLAY_label'] = {1, 7, 12, 0, false, nil},
    ['HMCS DISPLAY INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['HMCS DISPLAY INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['HMCS ALIGN HMCS_ALIGN_label'] = {1, 6, 10, 0, false, nil},
    ['HMCS ALIGN INS_SelectedSteerpoint'] = {1, 20, 2, 0, false, nil},
    ['HMCS ALIGN INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['HMCS DISPLAY HMCS_HUD_BLANK'] = {2, 3, 8, 0, false, nil},
    ['HMCS DISPLAY Asterisks_HUD_BLANK_both'] = {2, 2, 1, 11, true, nil},
    ['HMCS ALIGN HMCS_COARSE'] = {2, 2, 6, 0, false, nil},
    ['HMCS ALIGN Asterisks_COARSE_both'] = {2, 1, 1, 8, true, nil},
    ['HMCS DISPLAY HMCS_CKPT_BLANK'] = {3, 3, 9, 0, false, nil},
    ['HMCS DISPLAY Asterisks_CKPT_BLANK_both'] = {3, 2, 1, 12, true, nil},
    ['HMCS ALIGN HMCS_AZ_EL'] = {3, 2, 5, 0, false, nil},
    ['HMCS ALIGN Asterisks_AZ_ELAZ_EL_both'] = {3, 1, 1, 7, true, nil},
    ['HMCS DISPLAY HMCS_DECLUTTER'] = {4, 3, 14, 0, false, nil},
    ['HMCS DISPLAY HMCS_DECLUTTER_STATUS'] = {4, 17, 1, 0, false, nil},
    ['HMCS DISPLAY Asterisks_DECLUTTER_both'] = {4, 12, 1, 18, true, nil},
    ['HMCS ALIGN HMCS_ROLL'] = {4, 2, 4, 0, false, nil},
    ['HMCS ALIGN Asterisks_ROLL_both'] = {4, 1, 1, 6, true, nil},
    ['HMCS DISPLAY HMCS_RWR_DISPLAY'] = {5, 3, 9, 0, false, nil},
    ['HMCS DISPLAY HMCS_RWR_DISPLAY_STATUS'] = {5, 13, 3, 0, false, nil},
    ['HMCS DISPLAY Asterisks_RWR_DISPLAY_both'] = {5, 12, 1, 16, true, nil},

    -- BULL
    ['BULLSEYE LABEL'] = {1, 6, 8, 0, false, nil},
    ['BULLSEYE LABEL Asteriscs_both'] = {1, 5, 1, 14, true, nil},
    ['BULL POINT LABEL'] = {2, 6, 4, 0, false, nil},
    ['BULLSEYE NUMBER'] = {2, 12, 4, 0, false, nil},
    ['BULLSEYE IncDecSymbol'] = {2, 16, 1, 0, false, nil},
    ['BULLSEYE SEQUENCE Asteriscs_both'] = {2, 11, 1, 15, true, nil},

    -- MARK
    ['MARK'] = {1, 1, 4, 0, false, nil},
    ['MARK SOURCE'] = {1, 7, 4, 0, false, nil},
    ['MARK SOURCE Asteriscs_both'] = {1, 6, 1, 11, true, nil},
    ['STPT NUMBER'] = {1, 14, 3, 0, false, nil},
    ['MARK IncDecSymbol'] = {1, 17, 1, 0, false, nil},
    ['MARK Number Asteriscs_both'] = {1, 13, 1, 18, true, nil},
    ['STPT'] = {1, 19, 4, 0, false, nil},
    ['MARK Latitude'] = {2, 2, 3, 0, false, nil},
    ['MARK Latitude Value'] = {2, 6, 12, 0, false, nil},
    ['MARK Latitude Asteriscs_both'] = {2, 5, 1, 18, true, nil},
    ['MARK Longitude'] = {3, 2, 3, 0, false, nil},
    ['MARK Longitude Value'] = {3, 6, 12, 0, false, nil},
    ['MARK Longitude Asteriscs_both'] = {3, 5, 1, 18, true, nil},
    ['MARK Elevation'] = {4, 1, 4, 0, false, nil},
    ['MARK Elevation Value'] = {4, 6, 8, 0, false, nil},
    ['MARK Elevation Asteriscs_both'] = {4, 5, 1, 14, true, nil},
    ['MARK MGRS'] = {5, 1, 4, 0, false, nil},
    ['MARK GRID DIGIT Value'] = {5, 6, 2, 0, false, nil},
    ['MARK GRID SYMBOL Value'] = {5, 8, 1, 0, false, nil},
    ['MARK SQUARE Value1'] = {5, 9, 1, 0, false, nil},
    ['MARK SQUARE Value2'] = {5, 10, 1, 0, false, nil},
    ['MARK EAST Value'] = {5, 12, 5, 0, false, nil},
    ['MARK Slash'] = {5, 17, 1, 0, false, nil},
    ['MARK NORTH Value'] = {5, 18, 5, 0, false, nil},
    ['MARK MGRS Asteriscs_both'] = {5, 5, 1, 23, true, nil},

    -- DEST_DIR
    ['DEST DIR DEST_DIR'] = {1, 2, 8, 0, false, nil},
    ['DEST DIR DEST_DIR_SelectedSteerpoint'] = {1, 12, 3, 0, false, nil},
    ['DEST DIR DEST_DIR_STPT_IncDecSymbol'] = {1, 16, 1, 0, false, nil},
    ['DEST DIR Asterisks_NUM_STEERPOINT_both'] = {1, 11, 1, 15, true, nil},
    ['DEST DIR DEST_LAT'] = {2, 3, 3, 0, false, nil},
    ['DEST DIR LAT'] = {2, 8, 12, 0, false, nil},
    ['DEST DIR Asterisks_LAT_both'] = {2, 7, 1, 20, true, nil},
    ['DEST DIR DEST_LON'] = {3, 3, 3, 0, false, nil},
    ['DEST DIR LON'] = {3, 8, 12, 0, false, nil},
    ['DEST DIR Asterisks_LON_both'] = {3, 7, 1, 20, true, nil},
    ['DEST DIR DEST_ELEV'] = {4, 2, 4, 0, false, nil},
    ['DEST DIR ELEV'] = {4, 8, 7, 0, false, nil},
    ['DEST DIR Asterisks_ELEV_both'] = {4, 7, 1, 15, true, nil},
    ['DEST DIR DEST_TOS'] = {5, 3, 3, 0, false, nil},
    ['DEST DIR TOS'] = {5, 8, 8, 0, false, nil},
    ['DEST DIR Asterisks_TOS_both'] = {5, 7, 1, 16, true, nil},
    ['DEST DIR P2lbl'] = {5, 21, 3, 0, false, nil},

    -- UTM DEST
    ['UTM DEST UTM_DEST'] = {1, 2, 8, 0, false, nil},
    ['UTM DEST UTM_DEST_SelectedSteerpoint'] = {1, 12, 3, 0, false, nil},
    ['UTM DEST UTM_DEST_STPT_IncDecSymbol'] = {1, 16, 1, 0, false, nil},
    ['UTM DEST Asterisks_NUM_STEERPOINT_both'] = {1, 11, 1, 15, true, nil},
    ['UTM DEST UTM_DEST_GRID'] = {2, 6, 4, 0, false, nil},
    ['UTM DEST GRID_DIGIT'] = {2, 12, 2, 0, false, nil},
    ['UTM DEST GRID_SYMBOL'] = {2, 14, 1, 0, false, nil},
    ['UTM DEST Asterisks_GRID_DIGIT_both'] = {2, 11, 1, 15, true, nil},
    ['UTM DEST Asterisks_GRID_SYMBOL_both'] = {2, 11, 1, 15, true, nil},
    ['UTM DEST UTM_DEST_CNVRT'] = {2, 18, 5, 0, false, nil},
    ['UTM DEST Asterisks_CNVRT_both'] = {2, 17, 1, 23, true, nil},
    ['UTM DEST UTM_DEST_SQUARE'] = {3, 4, 6, 0, false, nil},
    ['UTM DEST SQUARE'] = {3, 12, 1, 0, false, nil},
    ['UTM DEST SQUARE2'] = {3, 13, 1, 0, false, nil},
    ['UTM DEST Asterisks_SQUARE_both'] = {3, 11, 1, 14, true, nil},
    ['UTM DEST Asterisks_SQUARE2_both'] = {3, 11, 1, 14, true, nil},
    ['UTM DEST UTM_DEST_EAST/NORTH'] = {4, 0, 10, 0, false, nil},
    ['UTM DEST EAST/NORTH'] = {4, 12, 11, 0, false, nil},
    ['UTM DEST Asterisks_EAST/NORTH_both'] = {4, 11, 1, 23, true, nil},
    ['UTM DEST UTM_DEST_ELEV'] = {5, 6, 4, 0, false, nil},
    ['UTM DEST ELEV'] = {5, 12, 7, 0, false, nil},
    ['UTM DEST Asterisks_ELEV_both'] = {5, 11, 1, 19, true, nil},
    ['UTM DEST P1 lbl'] = {5, 21, 3, 0, false, nil},

    -- DEST_OA1
    ['DEST OA1 DEST_OA1'] = {1, 2, 8, 0, false, nil},
    ['DEST OA1 DEST_OA1_SelectedSteerpoint'] = {1, 11, 3, 0, false, nil},
    ['DEST OA1 DEST_OA1_STPT_IncDecSymbol'] = {1, 15, 1, 0, false, nil},
    ['DEST OA1 Asterisks_NUM_STEERPOINT'] = {1, 10, 1, 14, true, nil},
    ['DEST OA1 Asterisks_NUM_STEERPOINT_both'] = {1, 10, 1, 14, true, nil},
    ['DEST OA1 DEST_OA1_RNG'] = {3, 3, 3, 0, false, nil},
    ['DEST OA1 RNG'] = {3, 8, 8, 0, false, nil},
    ['DEST OA1 Asterisks_RNG_both'] = {3, 7, 1, 16, true, nil},
    ['DEST OA1 DEST_OA1_BRG'] = {4, 3, 3, 0, false, nil},
    ['DEST OA1 BRG'] = {4, 8, 6, 0, false, nil},
    ['DEST OA1 Asterisks_BRG_both'] = {4, 7, 1, 14, true, nil},
    ['DEST OA1 DEST_OA1_ELEV'] = {5, 2, 3, 0, false, nil},
    ['DEST OA1 ELEV'] = {5, 8, 8, 0, false, nil},
    ['DEST OA1 Asterisks_ELEV_both'] = {5, 7, 1, 16, true, nil},
    ['DEST OA1 P3lbl'] = {5, 21, 3, 0, false, nil},

    -- DEST_OA2
    ['DEST OA2 DEST_OA2'] = {1, 2, 8, 0, false, nil},
    ['DEST OA2 DEST_OA2_SelectedSteerpoint'] = {1, 11, 3, 0, false, nil},
    ['DEST OA2 DEST_OA2_STPT_IncDecSymbol'] = {1, 15, 1, 0, false, nil},
    ['DEST OA2 Asterisks_NUM_STEERPOINT'] = {1, 10, 1, 14, true, nil},
    ['DEST OA2 Asterisks_NUM_STEERPOINT_both'] = {1, 10, 1, 14, true, nil},
    ['DEST OA2 DEST_OA2_RNG'] = {3, 3, 3, 0, false, nil},
    ['DEST OA2 RNG'] = {3, 8, 8, 0, false, nil},
    ['DEST OA2 Asterisks_RNG_both'] = {3, 7, 1, 16, true, nil},
    ['DEST OA2 DEST_OA2_BRG'] = {4, 3, 3, 0, false, nil},
    ['DEST OA2 BRG'] = {4, 8, 6, 0, false, nil},
    ['DEST OA2 Asterisks_BRG_both'] = {4, 7, 1, 14, true, nil},
    ['DEST OA2 DEST_OA2_ELEV'] = {5, 2, 3, 0, false, nil},
    ['DEST OA2 ELEV'] = {5, 8, 8, 0, false, nil},
    ['DEST OA2 Asterisks_ELEV_both'] = {5, 7, 1, 16, true, nil},
    ['DEST OA2 P4lbl'] = {5, 21, 3, 0, false, nil},

    -- CRUS TOS
    ['CRUS_MODE'] = {1, 7, 4, 0, false, nil},
    ['INS_SelectedSteerpoint'] = {1, 20, 3, 0, false, nil},
    ['INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['TOS_MODE'] = {1, 13, 3, 0, false, nil},
    ['Asterisks_TOS_MODE_both'] = {1, 12, 1, 16, true, nil},
    ['TOS_SYSTEM_TIME_label'] = {2, 7, 4, 0, false, nil},
    ['TOS_SYSTEM_TIME_value'] = {2, 13, 8, 0, false, nil},
    ['TOS_DES_TOS_label'] = {3, 4, 7, 0, false, nil},
    ['TOS_DES_TOS_value'] = {3, 13, 8, 0, false, nil},
    ['Asterisks_DES_TOS_both'] = {3, 12, 1, 21, true, nil},
    ['TOS_ETA_label'] = {4, 8, 3, 0, false, nil},
    ['TOS_ETA_value'] = {4, 13, 8, 0, false, nil},
    ['TOS_REQ_GS_label'] = {5, 4, 7, 0, false, nil},
    ['TOS_REQ_GS_value'] = {5, 13, 7, 0, false, nil},

    -- CRUS EDR
    ['EDR_MODE'] = {1, 13, 4, 0, false, nil},
    ['Asterisks_RNG_MODE_both'] = {1, 12, 1, 16, true, nil},
    ['EDR_STPT_NUM'] = {2, 7, 4, 0, false, nil},
    ['EDR_INS_SelectedSteerpoint'] = {2, 12, 3, 0, false, nil},
    ['EDR_INS_STPT_IncDecSymbol'] = {2, 16, 1, 0, false, nil},
    ['EDR_TO_BINGO_label'] = {3, 4, 7, 0, false, nil},
    ['EDR_TO_BINGO_value'] = {3, 13, 8, 0, false, nil},
    ['EDR_OPT_MACH_label'] = {4, 3, 8, 0, false, nil},
    ['EDR_OPT_MACH_value'] = {4, 13, 8, 0, false, nil},
    ['EDR_WIND_AT_ALTITUDE'] = {5, 7, 4, 0, false, nil},
    ['EDR_WIND_AT_ALTITUDE_Value'] = {5, 13, 10, 0, false, nil},

    -- CRUS HOME
    ['HOME CRUS_MODE'] = {1, 7, 4, 0, false, nil},
    ['HOME HOME_MODE'] = {1, 13, 4, 0, false, nil},
    ['HOME Asterisks_RNG_MODE_both'] = {1, 12, 1, 17, true, nil},
    ['HOME HOME_STPT_NUM'] = {2, 7, 4, 0, false, nil},
    ['HOME Asterisks_HOME_STPT_NUM_both'] = {2, 11, 1, 17, true, nil},
    ['HOME HOME_INS_SelectedSteerpoint'] = {2, 12, 3, 0, false, nil},
    ['HOME HOME_INS_STPT_IncDecSymbol'] = {2, 16, 1, 0, false, nil},
    ['HOME HOME_FUEL_REMANING'] = {3, 7, 4, 0, false, nil},
    ['HOME HOME_FUEL_REMANING_Value'] = {3, 12, 8, 0, false, nil},
    ['HOME HOME_OPT_ALT_label'] = {4, 4, 7, 0, false, nil},
    ['HOME HOME_OPT_ALT_value'] = {4, 13, 8, 0, false, nil},
    ['HOME HOME_WIND_AT_ALTITUDE'] = {5, 7, 4, 0, false, nil},
    ['HOME HOME_WIND_AT_ALTITUDE_Value'] = {5, 13, 10, 0, false, nil},

    -- CRUS RNG
    ['RNG_MODE'] = {1, 13, 3, 0, false, nil},
    ['Asterisks_RNG_MODE_both'] = {1, 12, 1, 16, true, nil},
    ['RNG_STPT_NUM'] = {2, 7, 4, 0, false, nil},
    ['RNG_INS_SelectedSteerpoint'] = {2, 12, 3, 0, false, nil},
    ['RNG_INS_STPT_IncDecSymbol'] = {2, 16, 1, 0, false, nil},
    ['RNG_FUEL_REMANING'] = {3, 7, 4, 0, false, nil},
    ['RNG_FUEL_REMANING_Value'] = {3, 12, 8, 0, false, nil},
    ['RNG_WIND_AT_ALTITUDE'] = {5, 7, 4, 0, false, nil},
    ['RNG_WIND_AT_ALTITUDE_Value'] = {5, 13, 10, 0, false, nil},

    -- FIX
    ['FIX FIX_SENSORS'] = {1, 6, 3, 0, false, nil},
    ['FIX FIX_SelectedSensors'] = {1, 11, 4, 0, false, nil},
    ['FIX Asterisks_FIX_SENSORS_both'] = {1, 10, 1, 15, true, nil},
    ['FIX FIX_STPT'] = {2, 4, 4, 0, false, nil},
    ['FIX INS_SelectedSteerpoint'] = {2, 10, 3, 0, false, nil},
    ['FIX Asterisks_STPT_NUMBER_both'] = {2, 9, 1, 13, true, nil},
    ['FIX INS_STPT_IncDecSymbol'] = {2, 14, 1, 0, false, nil},
    ['FIX FIX_DELTA'] = {3, 3, 5, 0, false, nil},
    ['FIX DELTA'] = {3, 13, 7, 0, false, nil},
    ['FIX SYS ACCURACY label'] = {4, 4, 9, 0, false, nil},
    ['FIX SYS ACCURACY value'] = {4, 14, 4, 0, false, nil},
    ['FIX GPS ACCURACY label'] = {5, 4, 9, 0, false, nil},
    ['FIX GPS ACCURACY value'] = {5, 14, 4, 0, false, nil},

    -- A CAL MAN
    ['ACAL ACAL_SENSORS'] = {1, 1, 4, 0, false, nil},
    ['ACAL ACAL_SelectedSensors'] = {1, 8, 4, 0, false, nil},
    ['ACAL Asterisks_ACAL_SENSORS_both'] = {1, 7, 1, 12, true, nil},
    ['ACAL ACAL_ALT_label'] = {1, 14, 4, 0, false, nil},
    ['ACAL ACAL_MODE'] = {2, 8, 4, 0, false, nil},
    ['ACAL Asterisks_ACAL_SelectedMode_both'] = {2, 7, 1, 12, true, nil},
    ['ACAL ACAL_ALEV'] = {3, 8, 4, 0, false, nil},
    ['ACAL ELEV'] = {3, 16, 7, 0, false, nil},
    ['ACAL Asterisks_ELEV_both'] = {3, 15, 1, 23, true, nil},
    ['ACAL ACAL_ALT_DELTA'] = {4, 8, 5, 0, false, nil},
    ['ACAL ACAL_ALT_DELTA_label'] = {4, 2, 8, 0, false, nil},
    ['ACAL DELTA_ALT'] = {4, 16, 7, 0, false, nil},
    ['ACAL ACAL_POS_DELTA'] = {5, 8, 5, 0, false, nil},
    ['ACAL ACAL_POS_DELTA_label'] = {5, 2, 3, 0, false, nil},
    ['ACAL DELTA_POS'] = {5, 16, 7, 0, false, nil},

    -- A CAL AUTO
    ['INS_SelectedSteerpoint'] = {1, 20, 3, 0, false, nil},
    ['INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['AUTO_ACAL'] = {1, 1, 9, 0, false, nil},
    ['ACAL_AUTO_Sensors'] = {1, 12, 4, 0, false, nil},
    ['Asterisks_AUTO_both'] = {1, 11, 1, 16, true, nil},
    ['NAV_FILTER_label'] = {2, 2, 10, 0, false, nil},
    ['NAV_FILTER_mode'] = {2, 14, 4, 0, false, nil},
    ['GPS_ACCURACY_label'] = {3, 3, 9, 0, false, nil},
    ['GPS_ACCURACY_value'] = {3, 14, 4, 0, false, nil},
    ['DTS_STATUS_label'] = {4, 9, 3, 0, false, nil},
    ['DTS_STATUS_value'] = {4, 14, 3, 0, false, nil},
    ['DTS_ACCURACY_HPU_label'] = {4, 21, 2, 0, false, nil},
    ['DTS_ACCURACY_HPU_value'] = {4, 23, 1, 0, false, nil},
    ['DTS_ACCURACY_VPU_label'] = {5, 21, 2, 0, false, nil},
    ['DTS_ACCURACY_VPU_value'] = {5, 23, 1, 0, false, nil},

    -- HTS MAN
    ['HTS MAN HTS'] = {1, 8, 7, 0, false, nil},
    ['HTS MAN INS_SelectedSteerpoint'] = {1, 20, 3, 0, false, nil},
    ['HTS MAN INS_STPT_IncDecSymbol'] = {1, 23, 1, 0, false, nil},
    ['HTS MAN T1'] = {2, 1, 1, 0, false, nil},
    ['HTS MAN T1_code'] = {2, 3, 4, 0, false, nil},
    ['HTS MAN Asterisks_T1_both'] = {2, 2, 1, 7, true, nil},
    ['HTS MAN T5'] = {2, 10, 1, 0, false, nil},
    ['HTS MAN T5_code'] = {2, 12, 4, 0, false, nil},
    ['HTS MAN Asterisks_T5_both'] = {2, 11, 1, 16, true, nil},
    ['HTS MAN T2'] = {3, 1, 1, 0, false, nil},
    ['HTS MAN T2_code'] = {3, 3, 4, 0, false, nil},
    ['HTS MAN Asterisks_T2_both'] = {3, 2, 1, 7, true, nil},
    ['HTS MAN T6'] = {3, 10, 1, 0, false, nil},
    ['HTS MAN T6_code'] = {3, 12, 4, 0, false, nil},
    ['HTS MAN Asterisks_T6_both'] = {3, 11, 1, 16, true, nil},
    ['HTS MAN T3'] = {4, 1, 1, 0, false, nil},
    ['HTS MAN T3_code'] = {4, 3, 4, 0, false, nil},
    ['HTS MAN Asterisks_T3_both'] = {4, 2, 1, 7, true, nil},
    ['HTS MAN T7'] = {4, 10, 1, 0, false, nil},
    ['HTS MAN T7_code'] = {4, 12, 4, 0, false, nil},
    ['HTS MAN Asterisks_T7_both'] = {4, 11, 1, 16, true, nil},
    ['HTS MAN T4'] = {5, 1, 1, 0, false, nil},
    ['HTS MAN T4_code'] = {5, 3, 4, 0, false, nil},
    ['HTS MAN Asterisks_T4_both'] = {5, 2, 1, 7, true, nil},
    ['HTS MAN T8'] = {5, 10, 1, 0, false, nil},
    ['HTS MAN T8_code'] = {5, 12, 4, 0, false, nil},
    ['HTS MAN Asterisks_T8_both'] = {5, 11, 1, 16, true, nil},

    -- HTS SEAD
    ['HTS'] = {1, 4, 4, 0, false, nil},
    ['HTS_LAT_lbl'] = {2, 2, 3, 0, false, nil},
    ['HTS_LAT'] = {2, 7, 10, 0, false, nil},
    ['HTS_LNG_lbl'] = {3, 2, 3, 0, false, nil},
    ['HTS_LNG'] = {3, 7, 10, 0, false, nil},
    ['HTS_ELEV_lbl'] = {4, 2, 3, 0, false, nil},
    ['HTS_ELEV'] = {4, 7, 10, 0, false, nil},
    ['HTS_TOT_lbl'] = {5, 2, 3, 0, false, nil},
    ['HTS_TOT'] = {5, 7, 10, 0, false, nil},
}

local function parse_indication(indication_text)
    local parsed_data = {}
    for key, value in indication_text:gmatch('-+\n([^\n]+)\n([^\n]*)\n') do
        parsed_data[key] = value
    end
    return parsed_data
end

local function inverse_text(text)
    local new_text = {}
    for i, code in ipairs({text:byte(1, text:len())}) do
        new_text[i] = code + 128
    end
    return string.char(table.unpack(new_text))
end

local function merge_string(original_string, new_string, location)
	local new_string_length = new_string:len()
	local before = original_string:sub(1, location)
	local after = original_string:sub(location + new_string_length + 1)
    local merged = {}

	for i = 1, new_string_length do
		local current = original_string:sub(location + i, location + i)
		if current ~= ' ' then
			merged[i] = current
		else
			merged[i] = new_string:sub(i, i)
		end
	end
	return before .. table.concat(merged) .. after
end

local ded_formatter = {}

local blank_line = "                        "
function ded_formatter.format_ded_lines(indication_text)
    local lines = {blank_line, blank_line, blank_line, blank_line, blank_line}
    local ded_data = parse_indication(indication_text)

    -- Check for present of Objects that indicate Duplicate Key Names that need resolving
	local key_prefix =  ded_data["Guard Label"] or
	                    ded_data["Mode label"] or
	                    ded_data["Event Occured"] or
	                    ded_data["ALOW label"] or
	                    ded_data["CMDS_BINGO_label"] or
	                    ded_data["INS_INFLT_ALGN_lbl"] or
	                    ded_data["INTRAFLIGHT lbl"] or
	                    ded_data["A-G DL lbl"] or -- DLNK A-G page: further action might be necessary
	                    ded_data["NAV Status lbl"] or
	                    ded_data["HMCS_DISPLAY_label"] or
	                    ded_data["HMCS_ALIGN_label"] or
	                    ded_data["UTM_DEST"] or
	                    ded_data["DEST_DIR"] or
	                    ded_data["DEST_OA1"] or
	                    ded_data["DEST_OA2"] or
	                    ded_data["Target to VRP Label"] or ded_data["Target to VRP Label_inv"] or
	                    ded_data["Visual initial point to TGT Label"] or ded_data["Visual initial point to TGT Label_inv"] or
	                    ded_data["HOME_MODE"] or ded_data["HOME_MODE_inv"] or
	                    ded_data["FIX_SENSORS"] or
	                    ded_data["ACAL_SENSORS"] or
	                    ded_data["HARM"] or
	                    (ded_data["HTS"] == "HTS MAN" and "HTS MAN") or
	                    ded_data["Master_mode_label"] or
	                    ded_data["NET STATUS lbl"] or
	                    ded_data["LINK16 STN lbl"] or
	                    ded_data["LINK16 lbl"] or
	                    ded_data["MISC Label"] or
	                    ded_data["LIST Label"] or
	                    ded_data["LASR LABEL"]

    for key, value in pairs(ded_data) do
		local label = key_prefix and key_prefix .. ' ' .. key or key
        local layout = layout_defs[label:gsub('_inv', '', 1):gsub('_lhs', '_both', 1)]
        if layout then
            value = layout[6] or value
            if layout[5] or label:find('_inv') then
                if value:len() < layout[3] then
                    value = value .. blank_line:sub(1, layout[2] - value:len())
                end
                value = inverse_text(value)
            end
            lines[layout[1]] = merge_string(lines[layout[1]], value, layout[2])
            if layout[4] > 0 then
                lines[layout[1]] = merge_string(lines[layout[1]], value, layout[4])
            end
        end
    end

    return lines
end

return ded_formatter
